services:
  aw_clickzone.admin.clickzone:
    class: Accurateweb\ContentHotspotBundle\Admin\ContentHotspotAdmin
    arguments: [~, %hotspot_entity%, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: text, label: Клик-зоны }

  aw_clickzone.twig.click_zone_extension:
    class: Accurateweb\ContentHotspotBundle\Twig\ContentHotspotTwigExtension
    arguments: [ '@doctrine.orm.entity_manager', '@aw_clickzone.admin.clickzone', '%hotspot_entity%', '@session', '%security_provider_name%' ]
    tags:
      - { name: twig.extension }